Allow apt mirrors
progmaticltd/homebox pull request #375
Opened 2024-04-06 19:05 UTC by diffway

2024-04-07 17:50 UTC, progmaticltd commented
Again, thanks for this MR, that could be useful to many users. 

Would you mind extending this idea a little, please ?

- If we want to let the user replace `deb.debian.org` by another mirror, then we need to organise this differently, IMHO. For instance, by creating a `mirror` variable, with the default being `deb.debian.org`, and then, allow the users to override them.
- Second, as this is a very sensitive value, then I would like to check that the value is valid before deploying the sources.list file, for instance by downloading first the release file (e.g. `https://debian.mirror.serversaustralia.com.au/debian/dists/bookworm/Release`)
- Last but not least, documentation will need to mention this at least.

Again, thanks for your idea, I never thought about this.

2024-04-08 19:57 UTC, diffway commented
1. Added `mirror` variable to 'system settings' of each `config/defaults/version-*.yml` file, added discriptive comment.

2. My skills at `ansible` are not very strong, so maybe checking code could be done more efficiently, but it passes:
```sh
ROLE=bootstrap ansible-playbook -e version=small check.yml
```
```
...
TASK [bootstrap : Initialise and update the packages repository] ***********************************
included: ~/Projects/homebox-all/homebox/roles/bootstrap/tasks/check/apt.yml for homebox

TASK [bootstrap : Check apt mirror is valid for us] ************************************************
ok: [homebox] => (item=bookworm)
ok: [homebox] => (item=bookworm-updates)
ok: [homebox] => (item=bookworm-backports)

TASK [bootstrap : Check if we can run apt update without error] ************************************
...
```

3. Added to section [System settings](https://homebox.readthedocs.io/en/main/30-define-your-config/#create-the-blank-configuration)  which is IMO self descriptive. Also I'am not sure how to rebuild `readthedocs`.

2024-04-10 19:37 UTC, progmaticltd commented
Thank you!
Sorry for the late answer, I will check this asap.

2024-04-11 06:09 UTC, progmaticltd requested changes

2024-04-11 06:09 UTC, progmaticltd commented on roles/bootstrap/tasks/install/apt.yml
I was suggesting a pre-test before running the playbook, but checking in Ansible is good as well, goo idea.

I usually tend to restrict the usage of `shell` when there is no corresponding module to do the same with a native module.

Here a version using the ansible uri module:

```yml
- name: Check apt mirror is valid for us
  register: mirror
  ansible.builtin.uri:
    url: http://{{ system.apt.mirror }}/debian/dists/{{ distribution_release }}/Release
    return_content: true
  loop:
    - "{{ system.release }}"
    - "{{ system.release }}-updates"
    - "{{ system.release }}-backports"
  loop_control:
    loop_var: distribution_release
```

You can forget about the content checking using regex, as the content will be thoroughly checked by `apt update` in the following tasks.

The purpose of the test is more to be sure the mirror is reachable from the server.

2024-04-11 06:09 UTC, progmaticltd commented on roles/bootstrap/vars/main.yml
>    - deb.debian.org
We then need to remove this line.

2024-05-09 22:02 UTC, diffway commented
I beleve I've implemented everything as discussed.

2024-05-25 18:27 UTC, arodier commented
Hello, diffway, sorry for the late answer.
Thank you very much, I am testing it right now, and I will come back to you.
The only issue I found so far, is the fact that `https` does not work with all the mirrors.

2024-05-30 11:37 UTC, arodier commented
Actually, don't do anything, I can automatically detect if the mirror is only compatible with http and write the template accordingly.

2024-12-27 12:28 UTC, diffway commented
@arodier could you kindly make a decision about those conflicts?
I honestly doesn't understand what I'm supposed to do:

the file `docs/30-define-your-config.md` is gone in `progmaticltd:dev`
the file `roles/bootstrap/vars/main.yml` looks fine to me.

2024-12-28 09:28 UTC, arodier commented
Sorry, I neglected this issue, I will come back to it in a few days, during holidays.

2026-01-29 15:45 UTC, diffway commented
Closing this as stale.

2026-01-29 15:45 UTC, closed without merging